export default {
  verticalExtraBig: 80,
  verticalBig: 60,
  vertical: 48,
  verticalSmall: 37,
  horizontalBig: 40,
  horizontal: 20,
  horizontalSmall: 18,
  horizontalExtraSmall: 14,
  radius: 5,
  radiusSmall: 3,
  radiusCircle: 50,
  elevation: 3,
  spaceBig: 32,
  space: 24,
  mediumSpace: 16,
  smallSpace: 14,
  miniSpace: 4,
  buttonHeight: 52,
  buttonWidth: 104,
};
